name: Build & Deploy to Sandbox on Hetzner

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout github Action'
        uses: actions/checkout@v4.1.7

#      - name: 'Download and extract translations'
#        uses: crowdin/github-action@v2.1.3
#        with:
#          command: 'download'
#          command_args: '--all --verbose'
#          source: ./src/core/i18n/en/translation.en.json
#          translation: ./src/core/i18n/%two_letters_code%/translation.%two_letters_code%.json
#
#          download_translations: false
#          upload_sources: false
#          upload_translations: false
#          push_translations: false
#          push_sources: false
#
#          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
#          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
#        env:
#          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
#          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: 'Build and push image'
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build -f Dockerfile . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/alkemio-web:${{ github.sha }} -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/alkemio-web:latest
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/alkemio-web:${{ github.sha }}

      - name: Install Kubectl
        uses: azure/setup-kubectl@v4.0.0
        with:
          version: 'v1.27.6' # Ensure this matches the version used in your cluster

      - name: Set up Kubeconfig for Hetzner k3s
        run: |
          mkdir -p $HOME/.kube  # Ensure the .kube directory exists
          echo "${{ secrets.KUBECONFIG_SECRET_HETZNER_SANDBOX }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Create Image Pull Secret
        run: |
          kubectl create secret docker-registry alkemio-web-secret \
            --docker-server=${{ secrets.REGISTRY_LOGIN_SERVER }} \
            --docker-username=${{ secrets.REGISTRY_USERNAME }} \
            --docker-password=${{ secrets.REGISTRY_PASSWORD }} \
            --dry-run=client -o yaml | kubectl apply -f -

      - uses: azure/k8s-deploy@v5.0.0
        with:
          manifests: |
            manifests/26-web-deployment-test.yaml
            manifests/30-web-service.yaml
          images: |
            ${{ secrets.REGISTRY_LOGIN_SERVER }}/alkemio-web:${{ github.sha }}
          imagepullsecrets: |
            alkemio-web-secret
